# Generated by Django 3.1.2 on 2020-10-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_id', models.CharField(blank=True, max_length=20)),
                ('C_name', models.CharField(blank=True, max_length=50)),
                ('C_email', models.EmailField(max_length=254)),
                ('C_address', models.TextField(max_length=100)),
                ('C_contact', models.CharField(blank=True, max_length=20)),
                ('delivary_date', models.DateTimeField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
