# Generated by Django 3.1.2 on 2020-10-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Delivery_date',
            field=models.DateField(),
        ),
    ]
