# Generated by Django 3.1.2 on 2020-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20201022_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
